"""
The cross-language commitment.

The vectors these tests replay were generated by the dashboard's own
``frontend/src/lib/canonical.ts`` (see ``vectors/generate_vectors.mjs``). If this
file goes red, a trail this orchestrator commits will fail verification in the
browser — which is the one failure mode the whole design exists to rule out.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import pytest

from praxis.canonical import TRAIL_BODY_KEYS, canonical_trail_json, canonicalize, hash_trail

VECTORS = json.loads(
    (Path(__file__).parent / "vectors" / "trail_vectors.json").read_text(encoding="utf-8")
)["vectors"]


@pytest.mark.parametrize("vector", VECTORS, ids=[v["name"] for v in VECTORS])
def test_matches_the_typescript_serialisation(vector):
    assert canonical_trail_json(vector["body"]) == vector["canonical"]


@pytest.mark.parametrize("vector", VECTORS, ids=[v["name"] for v in VECTORS])
def test_matches_the_typescript_hash(vector):
    assert hash_trail(vector["body"]) == vector["trailHash"]


def test_vectors_cover_the_divergences_that_matter():
    """A guard on the guard: these are the cases a naive port gets wrong."""
    names = {v["name"] for v in VECTORS}
    assert {"key-order", "integral-floats", "non-ascii", "string-escapes"} <= names


def test_keys_are_sorted_recursively():
    body = {"z": 1, "a": {"z": 2, "a": 3}, "m": [{"z": 4, "a": 5}]}
    assert canonical_trail_json(body) == '{"a":{"a":3,"z":2},"m":[{"a":5,"z":4}],"z":1}'


def test_arrays_keep_their_order():
    assert canonical_trail_json({"xs": [3, 1, 2]}) == '{"xs":[3,1,2]}'


def test_integral_floats_narrow_to_int():
    """JSON.stringify(4000.0) is "4000"; json.dumps(4000.0) would be "4000.0"."""
    assert canonical_trail_json({"n": 4000.0}) == '{"n":4000}'
    assert canonical_trail_json({"n": 0.5}) == '{"n":0.5}'


def test_non_ascii_is_not_escaped():
    """ensure_ascii=False, to match JSON.stringify."""
    assert canonical_trail_json({"s": "révisé"}) == '{"s":"révisé"}'


def test_booleans_are_not_treated_as_ints():
    assert canonical_trail_json({"b": True, "i": 1}) == '{"b":true,"i":1}'


@pytest.mark.parametrize("value", [float("nan"), float("inf"), float("-inf")])
def test_non_finite_numbers_are_refused(value):
    """JavaScript would silently serialise these as null and the hashes would diverge."""
    with pytest.raises(ValueError):
        canonical_trail_json({"n": value})


def test_non_string_keys_are_refused():
    with pytest.raises(TypeError):
        canonicalize({1: "a"})


def test_hash_is_keccak256_over_the_canonical_bytes():
    from eth_utils import keccak

    body = {"b": 2, "a": 1}
    expected = "0x" + keccak(text='{"a":1,"b":2}').hex()
    assert hash_trail(body) == expected


def test_hash_is_stable_across_key_order():
    assert hash_trail({"a": 1, "b": 2}) == hash_trail({"b": 2, "a": 1})


def test_hash_changes_when_any_field_changes():
    base = {"attestationId": 1, "reasoning": "because"}
    assert hash_trail(base) != hash_trail({**base, "reasoning": "because."})


def test_trail_body_keys_are_the_ones_the_dashboard_recomputes():
    """``verifyTrail`` in api.ts strips source/model/trailHash and hashes the rest."""
    assert set(TRAIL_BODY_KEYS) == {
        "attestationId",
        "agentId",
        "policy",
        "inputs",
        "reasoning",
        "output",
        "nonce",
    }


def test_canonical_json_is_parseable_back(subtests=None):
    for vector in VECTORS:
        assert json.loads(vector["canonical"]) == json.loads(
            json.dumps(canonicalize(vector["body"]))
        )


def test_deeply_nested_bodies_round_trip():
    body = {"a": {"b": {"c": {"d": [1, {"f": 2.0, "e": math.pi}]}}}}
    assert json.loads(canonical_trail_json(body))["a"]["b"]["c"]["d"][1]["f"] == 2
