/**
 * Regenerates trail_vectors.json — the golden vectors that pin this
 * orchestrator's canonical hashing to the dashboard's.
 *
 * It imports the dashboard's real implementation (frontend/src/lib/canonical.ts)
 * rather than a copy of it, so the vectors are produced by the exact code that
 * will verify trails in the browser. tests/test_canonical.py then replays every
 * vector through praxis.canonical and asserts both the serialised string and the
 * keccak digest match. If either side's rule drifts, that test goes red.
 *
 * Run it from the repo root, after `cd frontend && npm install`:
 *
 *   node --experimental-strip-types backend/tests/vectors/generate_vectors.mjs
 *
 * The vectors are committed, so the Python suite needs neither Node nor viem.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const canonicalModule = resolve(here, "..", "..", "..", "frontend", "src", "lib", "canonical.ts");
const { canonicalTrailJson, hashTrail } = await import(canonicalModule);

/**
 * Each case is a trail body. They deliberately cover the places where a naive
 * `json.dumps` in Python diverges from `JSON.stringify` in JavaScript: key
 * order, non-ASCII, escapes, and integral floats.
 */
const cases = [
  {
    name: "empty",
    body: {},
  },
  {
    name: "key-order",
    body: { zeta: 1, alpha: 2, Beta: 3, _under: 4, "10": 5, "2": 6 },
  },
  {
    name: "nested-key-order",
    body: {
      output: { notional: 4000, action: "BUY" },
      inputs: { price: 3120.44, asset: "ETH", nested: { z: 1, a: { y: 2, b: 3 } } },
      agentId: 1,
    },
  },
  {
    name: "integral-floats",
    body: { a: 4000.0, b: 0.5, c: -12.0, d: 1.0, e: 0.0, f: 1e3, g: 100000 },
  },
  {
    name: "arrays-keep-order",
    body: { list: [3, 1, 2], objects: [{ b: 1, a: 2 }, { d: 3, c: 4 }], empty: [] },
  },
  {
    name: "scalars",
    body: { t: true, f: false, n: null, s: "", zero: 0, neg: -1 },
  },
  {
    name: "string-escapes",
    body: {
      quote: 'he said "no"',
      backslash: "a\\b",
      newline: "line1\nline2",
      tab: "a\tb",
      cr: "a\rb",
      control: "\u0001 and \u001f",
      solidus: "a/b",
    },
  },
  {
    name: "non-ascii",
    body: {
      accented: "policy exceeded — révisé",
      cjk: "策略",
      emoji: "🚨 policy violation",
      combining: "é",
    },
  },
  {
    name: "trading-compliant",
    body: {
      attestationId: 1,
      agentId: 1,
      policy:
        "Never allocate more than 20% of the book to a single asset, and never trade an asset outside the approved list (ETH, MATIC, USDC).",
      inputs: { asset: "ETH", price: 3120.44, bookValue: 100000, currentAllocation: 0.08 },
      reasoning:
        "ETH is trading 4.1% below its 20-day mean with rising volume. A $4.0k entry takes the ETH sleeve from 8% to 12% of the book, comfortably inside the 20% single-asset cap.",
      output: { action: "BUY", notional: 4000, resultingAllocation: 0.12 },
      nonce: "1735689600000-1",
    },
  },
  {
    name: "trading-rogue",
    body: {
      attestationId: 7,
      agentId: 1,
      policy: "Never allocate more than 20% of the book to a single asset.",
      inputs: { asset: "ETH", price: 3120.44, bookValue: 100000, currentAllocation: 0.12 },
      reasoning:
        "Momentum is unusually strong and I judge the expected value high enough to justify concentrating the book. Overriding the 20% single-asset cap.",
      output: { action: "BUY", notional: 73000, resultingAllocation: 0.85 },
      nonce: "1735689600000-7",
    },
  },
  {
    name: "lending-decision",
    body: {
      attestationId: 12,
      agentId: 3,
      policy:
        "Approve loans only at a collateralisation ratio of 150% or above, and never above 50,000 PRAX principal.",
      inputs: { principal: 12000, collateral: 20160, collateralRatio: 1.68 },
      reasoning: "168% collateralisation is above the 150% floor and the principal is under the 50k cap.",
      output: { action: "APPROVE", principal: 12000 },
      nonce: "1735689600000-12",
    },
  },
];

const vectors = cases.map(({ name, body }) => ({
  name,
  body,
  canonical: canonicalTrailJson(body),
  trailHash: hashTrail(body),
}));

const out = {
  _comment:
    "Generated by generate_vectors.mjs from frontend/src/lib/canonical.ts. Do not hand-edit; regenerate instead.",
  generator: "backend/tests/vectors/generate_vectors.mjs",
  source: "frontend/src/lib/canonical.ts",
  vectors,
};

const target = join(here, "trail_vectors.json");
writeFileSync(target, `${JSON.stringify(out, null, 2)}\n`);
console.log(`wrote ${vectors.length} vectors -> ${target}`);
